### ISSUE TITLE
Website certificate has been revoked, expired

### ISSUE THREAD

**Issue by danielhoherd** [wolfgang42/yaml-multiline#17]
```
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
$ openssl s_client -connect yaml-multiline.info:443 </dev/null | openssl x509 -noout
2021-09-30T10:04:09-0700
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = yaml-multiline.info
verify error:num=10:certificate has expired
notAfter=Sep 30 02:30:43 2021 GMT
verify return:1
depth=0 CN = yaml-multiline.info
notAfter=Sep 30 02:30:43 2021 GMT
verify return:1
DONE
```

<img width="706" alt="Screen Shot 2021-09-30 at 10 07 13 AM" src="https://user-images.githubusercontent.com/1323808/135499981-240bc0d2-0794-4d1d-adf7-af4e7b5c96a6.png">

**Comment by wolfgang42** [comment]
Thanks for letting me know! Should be working again now.

Looks like certbot obtained the new certificate but nginx never picked it up; I think I need to configure something to reload nginx when a new cert is ready. I'll leave this issue open to remind me to do that soon.

**Comment by Kinrany** [comment]
Expired again! :D

Btw [Caddy](https://caddyserver.com/) can renew certificates with approximately zero effort!

**Comment by wolfgang42** [comment]
Aargh, nginx has been bounced and this issue has been bumped up my todo list. Thanks for the ping.

The trouble with Caddy is that, useful as it may be, I already *have* an nginx configuration set up. Given that I've not gotten round to poking the right line into the certbot config, I'm unlikely to figure out how to deploy a completely different webserver any time soon :-)

**Comment by wolfgang42** [comment]
Certbot has been informed about nginx via the `post-hook` setting, so this should work correctly next time. I'll close this issue since it's ostensibly fixed, and have made a note to double-check before the next expiry. (One of these days I should also look into setting up monitoring.)

Thanks all for bringing this to my attention so quickly after it failed!

**Comment by wolfgang42** [comment]
Followup: I'm pleased to report that `--post-hook="nginx -s reload"` has done the trick, and the server is now properly picking up the certs when they're renewed.

I also spent a few minutes last week setting up some basic monitoring using [Checkly](https://www.checklyhq.com/)’s generously provided and easy-to-use free tier, so I should now be alerted well in advance if this falls over, rather than finding out *after* it breaks and having to scramble to fix it.
