### ISSUE TITLE
Flow-scalars single-quotes behavior on multi-line strings

### ISSUE THREAD

**Issue by sqnando** [wolfgang42/yaml-multiline#22]
Hi thx for your work!

Am I understanding the document wrong or does ruby and python parsers behave different than stated? When using single-quotes with flow-scalars I get my newlines converted to a space instead of being kept in any way. These are my tests:

Python 3.11.8 with PyYAML-6.0.2:
```python
>>> print("key: 'one\nother'")
key: 'one
other'

>>> yaml.safe_load("key: 'one\nother'")
{'key': 'one other'}

>>> yaml.safe_load("key: 'one\n other'")
{'key': 'one other'}

>>> yaml.safe_load("key: 'one\n  other'")
{'key': 'one other'}

>>> yaml.safe_load("key: 'one\n\tother'")
{'key': 'one other'}
```

Ruby ruby 2.7.5p203, Psych with libyaml 0.2.5:
```ruby
> puts("key: 'one\nother'")
key: 'one
other'
=> nil

> YAML.load("key: 'one\nother'")
=> {"key"=>"one other"}

> YAML.load("key: 'one\n other'")
=> {"key"=>"one other"}

> YAML.load("key: 'one\n  other'")
=> {"key"=>"one other"}

> YAML.load("key: 'one\n\tother'")
=> {"key"=>"one other"}

> YAML.load("key: 'one\n\t\tother'")
=> {"key"=>"one other"}
```

**Comment by wolfgang42** [comment]
I don’t think your problem is related to how YAML works; I think you're being confused by the fact that Python and Ruby *also* use `\n` as an escape sequence, so the newline is being converted by the programming language before the YAML parser ever sees it.

That is, the following Python expression:
```python
"key: 'one\nother'"
```
Is being converted into the string:
```plain
key: 'one
other'
```
and only *then* gets read as YAML:
```yaml
key: 'one
other'
```
which, when a string is single-quoted, replaces single newlines with spaces:
```json
{"key": "one other"}
```

I think you will see the behavior you expect if you instead write `\\n`, so that the YAML parser sees the `\n` as a literal value:
```yaml
key: 'one\nother'
```
```json
{"key": "one\nother"}
```

Hope this helps.

**Comment by sqnando** [comment]
True, misinterpreted the doc. Thanks again for publishing it!
